// Code generated by "stringer -type configStreamKind config.go"; DO NOT EDIT

package main

import "fmt"

const _configStreamKind_name = "configStreamKindVideoWebMconfigStreamKindAudioOpus"

var _configStreamKind_index = [...]uint8{0, 25, 50}

func (i configStreamKind) String() string {
	if i < 0 || i >= configStreamKind(len(_configStreamKind_index)-1) {
		return fmt.Sprintf("configStreamKind(%d)", i)
	}
	return _configStreamKind_name[_configStreamKind_index[i]:_configStreamKind_index[i+1]]
}
